[workspace]
members = ["cli", "qr_gen", "wasm"]

# [profile.release]
# # Optimize wasm bundle for size
# # - https://doc.rust-lang.org/cargo/reference/profiles.html
# # - https://rustwasm.github.io/docs/book/reference/code-size.html
# lto = true
# opt-level = "z"
# strip = "debuginfo"
