[package]
name = "qrazy_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qrazy"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.2", features = ["derive"] }
image = "0.23"
qr_gen = { path = "../qr_gen" }
