name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Run checks on project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install rust-toolchain.toml toolchain
      run: rustup show

    - name: Restore .cargo and target directories
      id: cargo-target-cache-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          target
          /home/runner/.cargo
        key: ${{ runner.os }}-cargo-target-cache

    - run: cargo fmt -- --check

    - run: cargo clippy -- -W clippy::pedantic -D warnings

    - run: cargo test --workspace

    - run: cargo build --package qrazy_wasm --target wasm32-unknown-unknown

    - name: Cache .cargo and target directories
      id: cargo-target-cache-save
      uses: actions/cache/save@v3
      with:
        path: |
          target
          /home/runner/.cargo
        key: ${{ steps.cargo-target-cache-restore.outputs.cache-primary-key }}
