name: Deploy pages site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore Nix cache
      id: nix-cache-restore
      uses: actions/cache/restore@v3
      with:
        path: /home/runner/nix
        key: ${{ runner.os }}-nix-cache

    - name: Build site
      run: |
        nix --store /home/runner/nix build .#site
        # https://github.com/NixOS/nix/issues/2264
        mv result broken-result-link
        ln -s "/home/runner/nix$(readlink broken-result-link)" result

    - name: Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: result

    - name: Cache Nix
      id: nix--cache-save
      uses: actions/cache/save@v3
      with:
        path: /home/runner/nix
        key: ${{ steps.nix-cache-restore.outputs.cache-primary-key }}
