name: Deploy pages site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install rust-toolchain.toml toolchain
      run: rustup show

    - run: cargo build --package qrazy_wasm --target wasm32-unknown-unknown --release

    - run: cp target/wasm32-unknown-unknown/release/qrazy_wasm.wasm example-site/

    - name: Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: example-site
