name: Deploy pages site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install rust-toolchain.toml toolchain
      run: rustup show

    - name: Install Wasm binyaren
      run: |
        set -xe
        wget -O binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/version_113/binaryen-version_113-x86_64-linux.tar.gz
        tar -xvf binaryen.tar.gz
        rm binaryen.tar.gz
        mv binaryen-* binaryen

    - run: cargo build --package qrazy_wasm --target wasm32-unknown-unknown --release

    - name: Optimize Wasm binary and move it to example-site/
      run: ./binaryen/bin/wasm-opt -Oz -o example-site/qrazy_wasm.wasm target/wasm32-unknown-unknown/release/qrazy_wasm.wasm

    - name: Cleanup
      run: rm -rf binaryen

    - name: Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: example-site
